name = "LibGEOSMakie"
uuid = "1902729b-b4d4-4bb0-ae7d-e2f19e2a15fb"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
